# DSC 540 - Data Preparation #
## Weeks 7 & 8 - Term Project: Milestone 3 ##
## Manoj K Kola ##

#### Libraries Imported

##### HTML Parsing
- **lxml**: High-performance XML and HTML parser used by pandas for reading HTML tables
- **html5lib**: Alternative HTML parser that provides better compatibility with modern web pages
- **StringIO**: Utility for reading HTML content as a file-like object in memory

##### Data Processing
- **pandas**: Primary library for data manipulation, analysis, and working with structured data
- **numpy**: Fundamental package for numerical computing and array operations

##### Web Requests
- **requests**: Simple HTTP library for sending requests to websites and retrieving web content

##### Usage
These libraries form the foundation for web scraping workflows, enabling you to:
- Fetch HTML content from websites
- Parse and extract data from HTML tables
- Clean and manipulate the extracted data
- Perform numerical analysis on the results

In [184]:
# Import lxml parser (used by pandas to read HTML tables)
import lxml

# Import html5lib parser (alternative HTML parser)
import html5lib

# Import pandas for data manipulation and analysis
import pandas as pd

# Import numpy for numerical operations
import numpy as np

# Import requests to send HTTP requests to websites
import requests

# Import StringIO to read HTML content as a file-like object
from io import StringIO

### Read HTML tables from the Wikipedia page & Cleaning/Formatting Website Data


This code demonstrates how to extract tabular data from a Wikipedia page using Python's `requests` and `pandas` libraries.

##### Code Overview

The code below scrapes the Wikipedia page listing the busiest airports in the United States and extracts all HTML tables present on that page.

##### Step-by-Step Breakdown

1. **Define the target URL**: We specify the Wikipedia page containing airport traffic data
2. **Set request headers**: Browser headers are added to prevent the request from being blocked
3. **Fetch the webpage**: A GET request retrieves the HTML content
4. **Parse HTML content**: The response is converted into a format compatible with pandas
5. **Extract tables**: `pd.read_html()` automatically identifies and extracts all tables from the page
6. **Verify extraction**: The number of tables found is printed for confirmation

##### Key Components

- **URL**: Wikipedia page for busiest U.S. airports
- **User-Agent header**: Mimics a browser request to avoid potential blocking
- **`pd.read_html()`**: Pandas function that automatically parses HTML tables into DataFrames
- **Output**: A list of DataFrames, each representing a table from the webpage

##### Result

The script outputs the total number of tables extracted, which can then be individually examined and analyzed.

In [185]:
# Define the Wikipedia URL containing the airport data
url = "https://en.wikipedia.org/wiki/List_of_the_busiest_airports_in_the_United_States"

# Create headers to mimic a browser request (helps avoid request blocking)
headers = {"User-Agent": "Mozilla/5.0"}

# Send a GET request to the website and store the response
response = requests.get(url, headers=headers)

# Convert the HTML response text into a readable format for pandas
html = StringIO(response.text)

# Read all tables from the HTML page into a list of DataFrames
tables = pd.read_html(html)

# Count the total number of tables extracted from the Wikipedia page
num_tables = len(tables)

# Print the total number of tables found
print("Total tables extracted from the Wikipedia page:", num_tables)

Total tables extracted from the Wikipedia page: 10

#### Display Multiple Tables

This code snippet demonstrates how to loop through and display the first 3 tables from a collection of DataFrames in a clean, readable format.

**Key Components:**
- Uses `IPython.display` to render tables nicely in Jupyter
- Iterates through the first 3 tables with enumeration for tracking
- Adds clear separators between each table for better readability

In [186]:
# Import display function to nicely show tables in Jupyter Notebook
from IPython.display import display

# Loop through the first 3 tables from the list of tables
for i, table in enumerate(tables[:3]):
    
    # Print the table number for reference
    print(f"\n========== Table {i} ==========")
    
    # Display the current table in a readable format
    display(table)

========== Table 0 ==========

,Rank (2024),Airports (large),IATA Code,Major cities served,Metro area,State,2024[2],2023[3],2022[4],2021[5],2020[6],2019[7],2018[8],2017[9],2016[10],2015[11]
0,1,Hartsfield–Jackson Atlanta International Airport,ATL,Atlanta,Metro Atlanta,GA,52511402,50950068,45396001,36676010,20559866,53505795,51865797,50251964,50501858,49340732
1,2,Dallas/Fort Worth International Airport,DFW,Dallas and Fort Worth,Dallas–Fort Worth,TX,42351316,39246212,35345138,30005266,18593421,35778573,32821799,31816933,31283579,31589839
2,3,Denver International Airport,DEN,Denver,Greater Denver,CO,40012895,37863967,33773832,28645527,16243216,33592945,31362941,29809097,28267394,26280043
3,4,O'Hare International Airport,ORD,Chicago,Chicago,IL,38575693,35843104,33120474,26350976,14606034,40871223,39873927,38593028,37589899,36305668
4,5,Los Angeles International Airport,LAX,Los Angeles,Greater Los Angeles,CA,37760834,40956673,32326616,23663410,14055777,42939104,42624050,41232432,39636042,36351272
5,6,John F. Kennedy International Airport,JFK,New York City,New York Metro,NY,31466102,30804355,27154885,15273342,8269819,31036655,30620769,29533154,29239151,27782369
6,7,Charlotte Douglas International Airport,CLT,Charlotte,Greater Charlotte,NC,28523822,25896224,23100300,20900875,12952869,24199688,22281949,22011251,21511880,21913166
7,8,Harry Reid International Airport,LAS,Las Vegas,Las Vegas Valley,NV,28244966,27896199,25480500,19160342,10584059,24728361,23795012,23364393,22833267,21857693
8,9,Orlando International Airport,MCO,Orlando,Greater Orlando,FL,27859783,28033205,24469733,19618838,10467728,24562271,23202480,21565448,20283541,18759938
9,10,Miami International Airport,MIA,Miami,Miami Metro,FL,26588002,24717048,23949892,17500096,8786007,21421031,21021640,20709225,20875813,20986349
10,11,Phoenix Sky Harbor International Airport,PHX,Phoenix,Metro Phoenix,AZ,25595723,23880504,21852586,18940287,10531436,22433552,21622580,21185458,20896265,21351504
11,12,Seattle–Tacoma International Airport,SEA,Seattle and Tacoma,Seattle Metro,WA,25414592,24594210,22157862,17430195,9462411,25001762,24024908,22639124,21887110,20148980
12,13,San Francisco International Airport,SFO,San Francisco,San Francisco Bay Area,CA,25078968,24191159,20411420,11725347,7745057,27779230,27790717,26900048,25707101,24190560
13,14,Newark Liberty International Airport,EWR,Newark and New York City,New York Metro,NJ,24544320,24575320,21774690,14514049,7985474,23160763,22797602,21571198,19923009,18684818
14,15,George Bush Intercontinental Airport,IAH,Houston,Greater Houston,TX,23349157,22228844,19814052,16242821,8682558,21905309,21157398,19603731,20062072,20595881
15,16,Logan International Airport,BOS,Boston,Greater Boston,MA,21090721,19962678,17443775,10909817,6035452,20699377,20006521,18759742,17759044,16290362
16,17,Minneapolis–Saint Paul International Airport,MSP,Minneapolis and Saint Paul,Minneapolis–Saint Paul,MN,18054481,17019128,15242089,12211409,7069720,19192917,18361942,18409704,18123844,17634273
17,18,Fort Lauderdale–Hollywood International Airport,FLL,Fort Lauderdale and Hollywood,Miami Metro,FL,17096131,17063063,15370165,13598994,8015744,17950989,17612331,15817043,14263270,13061632
18,19,LaGuardia Airport,LGA,New York City,New York Metro,NY,16715567,16173073,14367463,7827307,4147116,15393601,15058501,14614802,14762593,14319924
19,20,Detroit Metropolitan Airport,DTW,Detroit,Detroit Metro,MI,16110696,15378601,13751197,11517696,6822324,18143040,17436837,17036092,16847135,16255520
20,21,Philadelphia International Airport,PHL,Philadelphia,Philadelphia Metro,PA,15102261,13656189,12421168,9820222,5753239,16006389,15292670,14271243,14564419,15101349
21,22,Salt Lake City International Airport,SLC,Salt Lake City,Wasatch Front,UT,13543570,12905368,12383843,10795906,5753239,12840841,12226730,11615954,11143738,10634538
22,23,Baltimore/Washington International Airport,BWI,"Baltimore and Washington, D.C.",Baltimore metropolitan area,MD,13221461,12849721,11151169,9253561,5451355,13284687,13371816,12976554,12340972,11738845
23,24,Dulles International Airport,IAD,"Washington, D.C.",Washington Metro,VA,13003234,12073571,10266324,7227875,3862658,11884117,11621623,11024306,10596942,10363974
24,25,San Diego International Airport,SAN,San Diego,Greater San Diego,CA,12780013,12190183,11162224,7836360,4637856,12648692,12174224,11139933,10340164,9985763
25,26,Ronald Reagan Washington National Airport,DCA,"Washington, D.C.",Washington Metro,VA,12750892,12365030,11553850,6731737,3573489,11595454,11367176,11506310,11470854,11242375
26,27,Tampa International Airport,TPA,Tampa,Tampa Bay area,FL,12075591,11677632,10539459,8847197,4966775,10978756,10368514,9548580,9194994,9150458
27,28,Nashville International Airport,BNA,Nashville,Greater Nashville,TN,12058688,11227243,9829062,7594049,4013995,8935654,8017347,6902771,6338517,5715205
28,29,Austin–Bergstrom International Airport,AUS,Austin,Greater Austin,TX,10678073,10833443,10382573,6666215,3141505,8683711,7921797,6973115,6095545,5797547
29,30,Daniel K. Inouye International Airport,HNL,Honolulu,Oahu,HI,10449022,10149761,8828395,5830928,3126391,9988678,9578505,9743989,9656340,9656340
30,31,Midway International Airport,MDW,Chicago,Chicago,IL,10360093,10659520,9650281,7680617,4236603,10081781,10678018,10912074,11044387,10830850

========== Table 1 ==========

,Rank (2024),Airports (medium hubs),IATA Code,City served,Metro Area,State,2024[2],2023[3],2022[4],2021[5],2020[6],2019[7],2018[8],2017[9],2016[10],2015[11]
0,32,Dallas Love Field,DAL,Dallas,Dallas–Fort Worth,TX,8654991,8559052,7819129,6487563,3669930,8408457,8134848,7876769,7554596,7040921
1,33,Portland International Airport,PDX,Portland,Portland,OR,8639088,8123054,7241882,5759879,3455877,9797408,9940866,9435473,9071154,8340234
2,34,St. Louis Lambert International Airport,STL,St. Louis,St. Louis,MO,7807362,7307561,6709080,5070471,3041765,7946986,7822274,7372805,6793076,6239231
3,35,Raleigh–Durham International Airport,RDU,Raleigh,Research Triangle,NC,7584394,7119040,5849665,4311049,2337496,6919429,6416822,5851004,5401714,4954717
4,36,William P. Hobby Airport,HOU,Houston,Houston,TX,7116967,6800329,6462948,5560780,3127178,7069614,6937061,6741870,6285181,5937944
5,37,Sacramento International Airport,SMF,Sacramento,Sacramento,CA,6679426,6371910,6040824,4760275,2710342,6454413,6031630,5460526,4969366,4816440
6,38,Louis Armstrong New Orleans International Airport,MSY,New Orleans,New Orleans,LA,6537092,6309212,5931899,4017147,2632606,6717105,6565482,6005527,5569705,5329696
7,39,Luis Muñoz Marín International Airport,SJU,San Juan,San Juan,PR,6490669,5985001,5039771,4738725,2362851,4590117,4033412,4163587,4343354,4218785
8,40,Kansas City International Airport,MCI,Kansas City,Kansas City,MO,5915078,5654068,4796476,3795290,2167616,5759419,5935131,5744918,5391557,5135127
9,41,Norman Y. Mineta San José International Airport,SJC,San Jose,San Francisco Bay Area,CA,5822019,5958855,5590137,3619690,2283186,7828885,7140616,6225148,5321603,4885690
10,42,San Antonio International Airport,SAT,San Antonio,San Antonio,TX,5466684,5336684,4751610,3677643,1919958,5022980,4844427,4521611,4179994,4091389
11,43,Southwest Florida International Airport,RSW,Fort Myers,Southwest Florida,FL,5425293,4963269,5132694,5080805,2947139,5144467,4719568,4461304,4350650,4231134
12,44,John Wayne Airport,SNA,Santa Ana,Greater Los Angeles,CA,5370273,5706332,5536313,3807205,1824836,5153276,5317149,5195047,5217242,4945175
13,45,Oakland San Francisco Bay Airport,OAK,Oakland,San Francisco Bay Area,CA,5292736,5520812,5506232,4011953,2271294,6560230,6798321,6530308,5934639,5506672
14,46,Indianapolis International Airport,IND,Indianapolis,Indianapolis,IN,5181947,4788376,4209416,3487100,1989126,4709183,4695040,4376432,4216766,3889567
15,47,Cleveland Hopkins International Airport,CLE,Cleveland,Cleveland,OH,4950345,4803822,4237795,3552402,1990156,4894541,4836580,4562740,4205739,4083476
16,48,Pittsburgh International Airport,PIT,Pittsburgh,Pittsburgh,PA,4862376,4493052,3918968,3069259,1742406,4715947,4670033,4327431,3986114,3890677
17,49,Cincinnati/Northern Kentucky International Air...,CVG,Cincinnati,Cincinnati,KY,4500414,4287722,3702997,3050597,1729395,4413457,4269258,3926158,3269979,3036697
18,50,John Glenn Columbus International Airport,CMH,Columbus,Columbus,OH,4387395,4095189,3618555,2825259,1577596,4172067,4054572,3765007,3567864,3312496
19,51,Palm Beach International Airport,PBI,West Palm Beach,Miami Metro,FL,4127211,3815977,3257730,2567897,1518732,3460429,3263042,3166532,3100624,3113485
20,52,Jacksonville International Airport,JAX,Jacksonville,Jacksonville,FL,3749791,3619739,3177393,2425685,1367501,3479923,3118540,2759067,2799587,2716465
21,53,Ontario International Airport,ONT,Ontario,Greater Los Angeles,CA,3494554,3181161,2840758,2201528,1237946,2723002,2499171,2247645,2127387,2089801
22,54,Kahului Airport,OGG,Kahului,Maui,HI,3415615,3745866,4125311,2933315,1135141,3791807,3572133,3442189,3352813,3220753
23,55,Hollywood Burbank Airport,BUR,Burbank,Greater Los Angeles,CA,3383237,3132029,3054729,1942417,1056838,2988720,2680240,2402106,2077892,1973897
24,56,Bradley International Airport,BDL,Hartford,Hartford,CT,3285194,3122212,2844713,2273259,1150033,3323614,3330734,3214976,2982194,2926047
25,57,Charleston International Airport,CHS,Charleston,Charleston,SC,3115194,3032768,2608497,2015277,944660,2375868,2192893,1945699,1811695,1669988
26,58,Milwaukee Mitchell International Airport,MKE,Milwaukee,Milwaukee,WI,3104054,2959840,2671281,2231010,1263385,3374073,3548817,3452544,3383271,3229876
27,59,Ted Stevens Anchorage International Airport,ANC,Anchorage,Anchorage,AK,2767856,2681818,2604308,2184959,1157301,2713843,2642901,2556188,2563524,2525876
28,60,Albuquerque International Sunport,ABQ,Albuquerque,Albuquerque,NM,2690218,2605163,2317836,1688646,868922,2641450,2647269,2412328,2341719,2323883
29,61,Eppley Airfield,OMA,Omaha,Omaha,NE,2583212,2464418,2204395,1829912,1036245,2455274,2457087,2303223,2127387,2046155
30,62,Buffalo Niagara International Airport,BUF,Buffalo,Buffalo–Niagara Falls,NY,2499295,2291995,2007508,1427891,703401,2459199,2523158,2348512,2313724,2331636
31,63,Boise Airport,BOI,Boise,Boise,ID,2475370,2369164,2230467,1809000,991241,2057750,1943181,1777642,1633507,1487777

========== Table 2 ==========

,Rank,Airport name,Location,IATA Code,2024[12],2023[13],2022[14],2021[15],2020[16],2019[17]
0,1,John F. Kennedy International Airport,"Queens, New York",JFK,34765387,32481057,25178878,12466165,8219317,33432159
1,2,Los Angeles International Airport,"Los Angeles, California",LAX,23438418,21503227,15940358,7862532,6246602,25210140
2,3,Miami International Airport,"Miami, Florida",MIA,23202731,21382328,18985551,11592445,6565834,20735658
3,4,San Francisco International Airport,"South San Francisco, California",SFO,15083931,13224356,9298781,3139041,3210024,14357960
4,5,Newark Liberty International Airport,"Newark, New Jersey",EWR,14690370,14080779,11344732,6250880,3688541,14087622
5,6,O'Hare International Airport,"Chicago, Illinois",ORD,13865434,13152578,10746991,5148494,3481860,13412885
6,7,Hartsfield–Jackson Atlanta International Airport,"College Park, Georgia",ATL,13813088,12088444,9543318,5474264,3347184,12268779
7,8,Dallas/Fort Worth International Airport,"Grapevine, Texas",DFW,11841330,10691190,8992922,5852397,3268822,9103438
8,9,George Bush Intercontinental Airport,"Houston, Texas",IAH,11675134,11279214,9124043,6458473,3491935,10764589
9,10,Washington Dulles International Airport,"Dulles, Virginia",IAD,10060851,8963807,6690447,3230027,1917510,7990292
10,11,General Edward Lawrence Logan International Ai...,"Boston, Massachusetts",BOS,8491518,7651625,5459853,2046561,1574712,7534504
11,12,Orlando International Airport,"Orlando, Florida",MCO,7610776,6696949,5214203,1837706,1525177,6957048
12,13,Fort Lauderdale–Hollywood International Airport,"Fort Lauderdale, Florida",FLL,6897993,7430312,6125500,4016553,2839383,8524251
13,14,Seattle–Tacoma International Airport,"SeaTac, Washington",SEA,6056779,5517422,4004180,1393603,1273179,5392147
14,15,Charlotte Douglas International Airport,"Charlotte, North Carolina",CLT,4623143,4140531,3183695,1989704,1069001,3405907
15,16,Denver International Airport,"Denver, Colorado",DEN,4444671,3823871,3222132,1856124,934563,3037012
16,17,Philadelphia International Airport,"Philadelphia, Pennsylvania",PHL,3704176,3518548,2613240,988733,682030,3847253
17,18,Harry Reid International Airport,"Paradise, Nevada",LAS,3592102,3133224,2439479,738257,711614,3462627
18,19,Daniel K. Inouye International Airport,"Honolulu, Hawaii",HNL,3533266,3134548,1565985,167502,1052697,5207875
19,20,Detroit Metropolitan Wayne County Airport,"Romulus, Michigan",DTW,3353501,2835905,2092098,966375,873744,3717775
20,21,Minneapolis–Saint Paul International Airport,"Saint Paul, Minnesota",MSP,3320850,2817694,1942385,673759,835721,3144386
21,22,Phoenix Sky Harbor International Airport,"Phoenix, Arizona",PHX,2821736,2481029,1957189,1223856,750138,1958468
22,23,LaGuardia Airport,"Queens, New York",LGA,1686395,1793314,1334733,309217,393011,2206518
23,24,Luis Muñoz Marín International Airport,"San Juan, Puerto Rico",SJU,1458172,1158996,802613,468287,253114,866088
24,25,Tampa International Airport,"Tampa, Florida",TPA,1384192,1178288,780245,167847,258738,1039740
25,26,Antonio B. Won Pat International Airport,"Tamuning, Guam",GUM,1342793,1192615,557359,98630,431890,2327930
26,27,Salt Lake City International Airport,"Salt Lake City, Utah",SLC,1311617,1250372,846680,578710,302640,1034704
27,28,Baltimore/Washington International Airport,"Linthicum Heights, Maryland",BWI,1156882,1201948,1006908,651636,341035,1104208
28,29,Austin–Bergstrom International Airport,"Austin, Texas",AUS,1064668,987214,818072,230835,81433,512989
29,30,San Diego International Airport,"San Diego, California",SAN,995537,904162,538005,200233,247218,1044516

#### Table Selection from Web Scraping Results

This code extracts the first three tables from a list of scraped tables and assigns them to separate DataFrames for further analysis.

**Purpose:**
- Separates multiple tables scraped from a web page into individual DataFrame objects
- Enables independent manipulation and analysis of each table
- Uses zero-based indexing to access tables from the `tables` list

**Variables Created:**
- `df_table0`: First table from the scraped data
- `df_table1`: Second table from the scraped data
- `df_table2`: Third table from the scraped data

In [187]:
# Select the first table from the list of scraped tables
df_table0 = tables[0]

# Select the second table from the list
df_table1 = tables[1]

# Select the third table from the list
df_table2 = tables[2]

#### Replace Headers

##### Data Preparation: Column Renaming

This section cleans up the column names in our airport passenger data to make them more consistent and easier to work with in our analysis.

##### Steps:

1. **Inspect Original Columns**: First, we examine the current column names to understand the data structure
2. **Rename Columns**: We apply systematic renaming to:
   - Simplify rank and location columns
   - Replace spaces with underscores for programmatic access
   - Remove footnote references from year columns
   - Create a consistent naming pattern for passenger count columns (2015-2024)
3. **Verify Changes**: Finally, we confirm the column names were updated correctly

##### Key Changes:
- `'Rank (2024)'` → `'Rank'`
- `'Airports (large)'` → `'Airport'`
- `'IATA Code'` → `'IATA_Code'`
- `'Major cities served'` → `'City'`
- `'Metro area'` → `'Metro_Area'`
- `'2024[2]'` → `'Passengers_2024'` (and similar for all years 2015-2024)

This standardized naming convention will make our subsequent data analysis and visualization code cleaner and more readable.

In [188]:
# Display the column names of the dataframe
df_table0.columns

Index(['Rank (2024)', 'Airports (large)', 'IATA Code', 'Major cities served',
       'Metro area', 'State', '2024[2]', '2023[3]', '2022[4]', '2021[5]',
       '2020[6]', '2019[7]', '2018[8]', '2017[9]', '2016[10]', '2015[11]'],
      dtype='object')

In [189]:
# Rename the columns to make them cleaner and easier to use
df_table0 = df_table0.rename(columns={
    'Rank (2024)': 'Rank',                  # Simplify rank column name
    'Airports (large)': 'Airport',          # Rename airport column
    'IATA Code': 'IATA_Code',               # Replace space with underscore
    'Major cities served': 'City',          # Shorten column name
    'Metro area': 'Metro_Area',             # Replace space with underscore
    'State': 'State',                       # Keep state column name consistent
    '2024[2]': 'Passengers_2024',           # Remove footnote and rename
    '2023[3]': 'Passengers_2023',
    '2022[4]': 'Passengers_2022',
    '2021[5]': 'Passengers_2021',
    '2020[6]': 'Passengers_2020',
    '2019[7]': 'Passengers_2019',
    '2018[8]': 'Passengers_2018',
    '2017[9]': 'Passengers_2017',
    '2016[10]': 'Passengers_2016',
    '2015[11]': 'Passengers_2015'
})

# Display the updated column names to verify the changes
df_table0.columns

Index(['Rank', 'Airport', 'IATA_Code', 'City', 'Metro_Area', 'State',
       'Passengers_2024', 'Passengers_2023', 'Passengers_2022',
       'Passengers_2021', 'Passengers_2020', 'Passengers_2019',
       'Passengers_2018', 'Passengers_2017', 'Passengers_2016',
       'Passengers_2015'],
      dtype='object')

#### Replace Headers

##### Data Preparation: Column Renaming

This section displays the original column names from `df_table1` and renames them for improved readability and consistency in analysis.

##### Steps:
1. **Display original columns**: View the current column structure
2. **Rename columns**: Apply standardized naming conventions
   - Remove year references from rank/airport columns
   - Add `Passengers_` prefix to yearly data columns
   - Replace spaces with underscores for programmatic access
3. **Verify changes**: Confirm the updated column names

##### Naming Conventions Applied:
- **Geographic data**: `Airport`, `IATA_Code`, `City`, `Metro_Area`, `State`
- **Passenger data**: `Passengers_YYYY` format (e.g., `Passengers_2024`)
- **Ranking**: Simplified to `Rank`

This standardization makes the dataset easier to analyze and visualize.

In [157]:
# Display the column names of df_table1
df_table1.columns

Index(['Rank (2024)', 'Airports (medium hubs)', 'IATA Code', 'City served',
       'Metro Area', 'State', '2024[2]', '2023[3]', '2022[4]', '2021[5]',
       '2020[6]', '2019[7]', '2018[8]', '2017[9]', '2016[10]', '2015[11]'],
      dtype='object')

In [190]:
# Rename columns to make them cleaner and easier to work with
df_table1 = df_table1.rename(columns={
    'Rank (2024)': 'Rank',
    'Airports (medium hubs)': 'Airport',
    'IATA Code': 'IATA_Code',
    'City served': 'City',
    'Metro Area': 'Metro_Area',
    'State': 'State',
    '2024[2]': 'Passengers_2024',
    '2023[3]': 'Passengers_2023',
    '2022[4]': 'Passengers_2022',
    '2021[5]': 'Passengers_2021',
    '2020[6]': 'Passengers_2020',
    '2019[7]': 'Passengers_2019',
    '2018[8]': 'Passengers_2018',
    '2017[9]': 'Passengers_2017',
    '2016[10]': 'Passengers_2016',
    '2015[11]': 'Passengers_2015'
})

# Display the updated column names to confirm changes
df_table1.columns

Index(['Rank', 'Airport', 'IATA_Code', 'City', 'Metro_Area', 'State',
       'Passengers_2024', 'Passengers_2023', 'Passengers_2022',
       'Passengers_2021', 'Passengers_2020', 'Passengers_2019',
       'Passengers_2018', 'Passengers_2017', 'Passengers_2016',
       'Passengers_2015'],
      dtype='object')

#### Replace Headers

##### Data Preparation: Column Inspection and Renaming
This section displays the original column names from `df_table2` and renames them for improved readability and consistency in analysis.

##### Steps:
1. **Display original columns**: View the current column structure
2. **Rename columns**: Apply standardized naming conventions
   - Remove year references from rank/airport columns
   - Add `Passengers_` prefix to yearly data columns
   - Replace spaces with underscores for programmatic access
3. **Verify changes**: Confirm the updated column names

##### Naming Conventions Applied:
- **Geographic data**: `Airport`, `IATA_Code`, `City`
- **Passenger data**: `Passengers_YYYY` format (e.g., `Passengers_2024`)

This standardization makes the dataset easier to analyze and visualize.

In [192]:
# Display the column names of the dataframe 'df_table2.'
df_table2.columns

Index(['Rank', 'Airport', 'City', 'IATA_Code', 'Passengers_2024',
       'Passengers_2023', 'Passengers_2022', 'Passengers_2021',
       'Passengers_2020', 'Passengers_2019'],
      dtype='object')

In [191]:
# Rename columns for better readability and consistency
# - Original column names from the Wikipedia table are replaced with more descriptive names
df_table2 = df_table2.rename(columns={
    'Rank': 'Rank',                     # Keep the rank column as is
    'Airport name': 'Airport',          # Rename 'Airport name' to 'Airport'
    'Location': 'City',                 # Rename 'Location' to 'City'
    'IATA Code': 'IATA_Code',           # Rename 'IATA Code' to 'IATA_Code'
    '2024[12]': 'Passengers_2024',     # Rename 2024 column to 'Passengers_2024'
    '2023[13]': 'Passengers_2023',     # Rename 2023 column to 'Passengers_2023'
    '2022[14]': 'Passengers_2022',     # Rename 2022 column to 'Passengers_2022'
    '2021[15]': 'Passengers_2021',     # Rename 2021 column to 'Passengers_2021'
    '2020[16]': 'Passengers_2020',     # Rename 2020 column to 'Passengers_2020'
    '2019[17]': 'Passengers_2019'      # Rename 2019 column to 'Passengers_2019'
})

# Display the updated column names to verify changes
df_table2.columns

Index(['Rank', 'Airport', 'City', 'IATA_Code', 'Passengers_2024',
       'Passengers_2023', 'Passengers_2022', 'Passengers_2021',
       'Passengers_2020', 'Passengers_2019'],
      dtype='object')

#### Format data into a more readable format
Fix casing and strip extra spaces in textual columns

##### Data Cleaning: Standardize Text Formatting
This code block cleans and standardizes the text formatting across three airport-related datasets (`df_table0`, `df_table1`, `df_table2`).

**Processing Steps:**
- **Airport names**: Converted to title case (e.g., "john f kennedy" → "John F Kennedy")
- **City names**: Converted to title case (e.g., "new york" → "New York")
- **State codes**: Converted to uppercase (e.g., "ny" → "NY")
- **Whitespace**: Extra leading/trailing spaces are removed from all the 3 fields

The code safely checks for column existence before applying transformations, ensuring it works even if some datasets have different structures.

In [162]:
# Loop through three datasets: df_table0, df_table1, df_table2
for df in [df_table0, df_table1, df_table2]:
    
    # If the 'Airport' column exists, convert to a string, remove extra spaces, and title-case it
    if 'Airport' in df.columns:
        df['Airport'] = df['Airport'].astype(str).str.strip().str.title()
    
    # If the 'City' column exists, convert to string, remove extra spaces, and title-case it
    if 'City' in df.columns:
        df['City'] = df['City'].astype(str).str.strip().str.title()
    
    # If the 'State' column exists, convert to string, remove extra spaces, and convert to uppercase
    if 'State' in df.columns:
        df['State'] = df['State'].astype(str).str.strip().str.upper()

# Print confirmation that the step is completed
print("Casing fixed and extra spaces removed for all three datasets.")

Casing fixed and extra spaces removed for all three datasets.

#### Replace Special characters like '/' & '–' from the Airport field

##### Airport Column Cleaning
This code cleans and standardizes the 'Airport' column across multiple dataframes by removing special characters and applying consistent formatting.


##### What it does
- Iterates through three dataframes: `df_table0`, `df_table1`, and `df_table2`
- Verifies the 'Airport' column exists before processing
- Applies a series of string transformations:
  - Converts all values to strings
  - Replaces forward slashes (/) with spaces
  - Replaces en dashes (–) with spaces
  - Removes extra whitespace
  - Capitalizes the first letter of each word

##### Example
**Before:** `"jfk/new–york  "`  
**After:** `"Jfk New York"`

In [163]:
# Loop through multiple dataframes to clean the 'Airport' column
for df in [df_table0, df_table1, df_table2]:
    
    # Check if the 'Airport' column exists in the current dataframe
    if 'Airport' in df.columns:
        
        # Clean and format the 'Airport' column
        df['Airport'] = (
            df['Airport']
            .astype(str)                  # Convert all values to string
            .str.replace('/', ' ', regex=False)  # Replace slashes with spaces
            .str.replace('–', ' ', regex=False)  # Replace dashes with spaces
            .str.strip()                  # Remove leading/trailing whitespace
            .str.title()                  # Capitalize each word
        )

#### Handle missing or inconsistent values

##### Data Cleaning: Handling Missing Values

This code loops through multiple dataframes (`df_table0`, `df_table1`, `df_table2`) to standardize the representation of missing values by replacing dash symbols (`-`) and empty strings with `NaN` values. This ensures consistency across all tables for subsequent analysis and makes it easier to identify and handle missing data using pandas' built-in methods.

In [193]:
# Loop through each dataframe in the list
for df in [df_table0, df_table1, df_table2]:
    # Replace '-' and empty strings with NaN for consistency
    df.replace({'-': np.nan, '': np.nan}, inplace=True)

# Print confirmation that the step is complete
print("Replaced missing or inconsistent values with NaN in all tables.")

Replaced missing or inconsistent values with NaN in all tables.

#### Identify & Drop Duplicates

##### Remove Duplicate Rows

Loop through each dataframe and remove any duplicate rows in-place. This ensures data quality by eliminating redundant entries across all three tables.

In [165]:
# Loop through each dataframe in the list
for df in [df_table0, df_table1, df_table2]:
    # Drop duplicate rows in-place for each dataframe
    df.drop_duplicates(inplace=True)

# Print confirmation that duplicates have been removed
print("Dropped duplicate rows (if present) in all three tables.")

Dropped duplicate rows (if present) in all three tables.

#### Calculate a New Column - Percentage Change Across Multiple DataFrames

This code loops through three dataframes (`df_table0`, `df_table1`, `df_table2`) and calculates the year-over-year percentage change in passenger counts between 2024 and 2023.

**Key Steps:**
- Iterates through each dataframe in the list
- Checks for the presence of both `Passengers_2024` and `Passengers_2023` columns
- Calculates percentage change using the formula: `((2024 - 2023) / 2023) × 100`
- Adds the result as a new column `Pct_Change_24_23` to each dataframe

**Output:** A confirmation message is printed once the percentage change column has been successfully added to all applicable tables.

In [166]:
# Loop through a list of dataframes to calculate percentage change
for df in [df_table0, df_table1, df_table2]:
    
    # Check if both 'Passengers_2024' and 'Passengers_2023' columns exist
    if 'Passengers_2024' in df.columns and 'Passengers_2023' in df.columns:
        
        # Calculate the percentage change between 2024 and 2023 passengers
        df['Pct_Change_24_23'] = (
            (df['Passengers_2024'] - df['Passengers_2023']) 
            / df['Passengers_2023']
        ) * 100  # Multiply by 100 to express as a percentage

# Print confirmation message
print("Added percentage change column (2024 vs 2023) to all applicable tables.")

Added percentage change column (2024 vs 2023) to all applicable tables.

#### Formatting Percentage Change Column

This code loops through multiple dataframes (`df_table0`, `df_table1`, `df_table2`) to format the `Pct_Change_24_23` column. For each dataframe:

1. **Checks** if the `Pct_Change_24_23` column exists
2. **Rounds** the values to 2 decimal places
3. **Converts** to string format and appends a '%' symbol

The formatting ensures consistent percentage display across all three tables, making year-over-year changes (2024 vs 2023) easier to read in the output.

In [167]:
# Loop through multiple dataframes to format the 'Pct_Change_24_23' column
for df in [df_table0, df_table1, df_table2]:
    
    # Check if the column exists in the dataframe
    if 'Pct_Change_24_23' in df.columns:
        
        # Round the values to 2 decimal places, convert to a string, and add a '%' sign
        df['Pct_Change_24_23'] = df['Pct_Change_24_23'].round(2).astype(str) + '%'

# Print confirmation that the formatting was applied
print("Added Pct_Change_24_23 with rounding and % sign.")

Added Pct_Change_24_23 with rounding and % sign.

#### Reset Index for Multiple DataFrames

This code resets the index for three cleaned datasets to ensure sequential row numbering starting from 0.

**What it does:**
- Iterates through three DataFrames: `df_table0`, `df_table1`, and `df_table2`
- Resets each DataFrame's index to a sequential range starting from 0
- The `drop=True` parameter discards the old index instead of adding it as a column
- The `inplace=True` parameter modifies the DataFrames directly without creating copies
- Prints a confirmation message when complete

In [169]:
# Reset the index for multiple dataframes
# We have three cleaned datasets (df_table0, df_table1, df_table2)
# Resetting the index ensures that the rows are numbered sequentially from 0

for df in [df_table0, df_table1, df_table2]:
    df.reset_index(drop=True, inplace=True)

# Print confirmation that all indices have been reset
print("Reset index for all three cleaned datasets.")

Reset index for all three cleaned datasets.

#### Cleaned Datasets Results

The following section displays the cleaned dataset after preprocessing, and data quality checks have been applied.

In [170]:
# Print a header and display the cleaned dataset
print("\n========== Cleaned Dataset ==========\n")

========== Cleaned Dataset ==========

#### Large Hub Airports - Table0 - Display DataFrame Contents

The following cell displays the contents of `df_table0`, which contains the data extracted from the table.

In [171]:
# Display the contents of the dataframe 'df_table0' in a Jupyter Notebook
display(df_table0)

,Rank,Airport,IATA_Code,City,Metro_Area,State,Passengers_2024,Passengers_2023,Passengers_2022,Passengers_2021,Passengers_2020,Passengers_2019,Passengers_2018,Passengers_2017,Passengers_2016,Passengers_2015,Pct_Change_24_23
0,1,Hartsfield Jackson Atlanta International Airport,ATL,Atlanta,Metro Atlanta,GA,52511402,50950068,45396001,36676010,20559866,53505795,51865797,50251964,50501858,49340732,3.06%
1,2,Dallas Fort Worth International Airport,DFW,Dallas And Fort Worth,Dallas–Fort Worth,TX,42351316,39246212,35345138,30005266,18593421,35778573,32821799,31816933,31283579,31589839,7.91%
2,3,Denver International Airport,DEN,Denver,Greater Denver,CO,40012895,37863967,33773832,28645527,16243216,33592945,31362941,29809097,28267394,26280043,5.68%
3,4,O'Hare International Airport,ORD,Chicago,Chicago,IL,38575693,35843104,33120474,26350976,14606034,40871223,39873927,38593028,37589899,36305668,7.62%
4,5,Los Angeles International Airport,LAX,Los Angeles,Greater Los Angeles,CA,37760834,40956673,32326616,23663410,14055777,42939104,42624050,41232432,39636042,36351272,-7.8%
5,6,John F. Kennedy International Airport,JFK,New York City,New York Metro,NY,31466102,30804355,27154885,15273342,8269819,31036655,30620769,29533154,29239151,27782369,2.15%
6,7,Charlotte Douglas International Airport,CLT,Charlotte,Greater Charlotte,NC,28523822,25896224,23100300,20900875,12952869,24199688,22281949,22011251,21511880,21913166,10.15%
7,8,Harry Reid International Airport,LAS,Las Vegas,Las Vegas Valley,NV,28244966,27896199,25480500,19160342,10584059,24728361,23795012,23364393,22833267,21857693,1.25%
8,9,Orlando International Airport,MCO,Orlando,Greater Orlando,FL,27859783,28033205,24469733,19618838,10467728,24562271,23202480,21565448,20283541,18759938,-0.62%
9,10,Miami International Airport,MIA,Miami,Miami Metro,FL,26588002,24717048,23949892,17500096,8786007,21421031,21021640,20709225,20875813,20986349,7.57%
10,11,Phoenix Sky Harbor International Airport,PHX,Phoenix,Metro Phoenix,AZ,25595723,23880504,21852586,18940287,10531436,22433552,21622580,21185458,20896265,21351504,7.18%
11,12,Seattle Tacoma International Airport,SEA,Seattle And Tacoma,Seattle Metro,WA,25414592,24594210,22157862,17430195,9462411,25001762,24024908,22639124,21887110,20148980,3.34%
12,13,San Francisco International Airport,SFO,San Francisco,San Francisco Bay Area,CA,25078968,24191159,20411420,11725347,7745057,27779230,27790717,26900048,25707101,24190560,3.67%
13,14,Newark Liberty International Airport,EWR,Newark And New York City,New York Metro,NJ,24544320,24575320,21774690,14514049,7985474,23160763,22797602,21571198,19923009,18684818,-0.13%
14,15,George Bush Intercontinental Airport,IAH,Houston,Greater Houston,TX,23349157,22228844,19814052,16242821,8682558,21905309,21157398,19603731,20062072,20595881,5.04%
15,16,Logan International Airport,BOS,Boston,Greater Boston,MA,21090721,19962678,17443775,10909817,6035452,20699377,20006521,18759742,17759044,16290362,5.65%
16,17,Minneapolis Saint Paul International Airport,MSP,Minneapolis And Saint Paul,Minneapolis–Saint Paul,MN,18054481,17019128,15242089,12211409,7069720,19192917,18361942,18409704,18123844,17634273,6.08%
17,18,Fort Lauderdale Hollywood International Airport,FLL,Fort Lauderdale And Hollywood,Miami Metro,FL,17096131,17063063,15370165,13598994,8015744,17950989,17612331,15817043,14263270,13061632,0.19%
18,19,Laguardia Airport,LGA,New York City,New York Metro,NY,16715567,16173073,14367463,7827307,4147116,15393601,15058501,14614802,14762593,14319924,3.35%
19,20,Detroit Metropolitan Airport,DTW,Detroit,Detroit Metro,MI,16110696,15378601,13751197,11517696,6822324,18143040,17436837,17036092,16847135,16255520,4.76%
20,21,Philadelphia International Airport,PHL,Philadelphia,Philadelphia Metro,PA,15102261,13656189,12421168,9820222,5753239,16006389,15292670,14271243,14564419,15101349,10.59%
21,22,Salt Lake City International Airport,SLC,Salt Lake City,Wasatch Front,UT,13543570,12905368,12383843,10795906,5753239,12840841,12226730,11615954,11143738,10634538,4.95%
22,23,Baltimore Washington International Airport,BWI,"Baltimore And Washington, D.C.",Baltimore metropolitan area,MD,13221461,12849721,11151169,9253561,5451355,13284687,13371816,12976554,12340972,11738845,2.89%
23,24,Dulles International Airport,IAD,"Washington, D.C.",Washington Metro,VA,13003234,12073571,10266324,7227875,3862658,11884117,11621623,11024306,10596942,10363974,7.7%
24,25,San Diego International Airport,SAN,San Diego,Greater San Diego,CA,12780013,12190183,11162224,7836360,4637856,12648692,12174224,11139933,10340164,9985763,4.84%
25,26,Ronald Reagan Washington National Airport,DCA,"Washington, D.C.",Washington Metro,VA,12750892,12365030,11553850,6731737,3573489,11595454,11367176,11506310,11470854,11242375,3.12%
26,27,Tampa International Airport,TPA,Tampa,Tampa Bay area,FL,12075591,11677632,10539459,8847197,4966775,10978756,10368514,9548580,9194994,9150458,3.41%
27,28,Nashville International Airport,BNA,Nashville,Greater Nashville,TN,12058688,11227243,9829062,7594049,4013995,8935654,8017347,6902771,6338517,5715205,7.41%
28,29,Austin Bergstrom International Airport,AUS,Austin,Greater Austin,TX,10678073,10833443,10382573,6666215,3141505,8683711,7921797,6973115,6095545,5797547,-1.43%
29,30,Daniel K. Inouye International Airport,HNL,Honolulu,Oahu,HI,10449022,10149761,8828395,5830928,3126391,9988678,9578505,9743989,9656340,9656340,2.95%
30,31,Midway International Airport,MDW,Chicago,Chicago,IL,10360093,10659520,9650281,7680617,4236603,10081781,10678018,10912074,11044387,10830850,-2.81%

#### Medium Hub Airports - Table1 - Display DataFrame

This cell displays the contents of `df_table1` in an interactive, formatted table in the Jupyter Notebook. The `display()` function provides a rich HTML representation of the DataFrame, making it easier to read and explore the data compared to a simple `print()` statement.

In [172]:
# Display the contents of the dataframe 'df_table1' in a readable format in Jupyter Notebook
display(df_table1)

,Rank,Airport,IATA_Code,City,Metro_Area,State,Passengers_2024,Passengers_2023,Passengers_2022,Passengers_2021,Passengers_2020,Passengers_2019,Passengers_2018,Passengers_2017,Passengers_2016,Passengers_2015,Pct_Change_24_23
0,32,Dallas Love Field,DAL,Dallas,Dallas–Fort Worth,TX,8654991,8559052,7819129,6487563,3669930,8408457,8134848,7876769,7554596,7040921,1.12%
1,33,Portland International Airport,PDX,Portland,Portland,OR,8639088,8123054,7241882,5759879,3455877,9797408,9940866,9435473,9071154,8340234,6.35%
2,34,St. Louis Lambert International Airport,STL,St. Louis,St. Louis,MO,7807362,7307561,6709080,5070471,3041765,7946986,7822274,7372805,6793076,6239231,6.84%
3,35,Raleigh Durham International Airport,RDU,Raleigh,Research Triangle,NC,7584394,7119040,5849665,4311049,2337496,6919429,6416822,5851004,5401714,4954717,6.54%
4,36,William P. Hobby Airport,HOU,Houston,Houston,TX,7116967,6800329,6462948,5560780,3127178,7069614,6937061,6741870,6285181,5937944,4.66%
5,37,Sacramento International Airport,SMF,Sacramento,Sacramento,CA,6679426,6371910,6040824,4760275,2710342,6454413,6031630,5460526,4969366,4816440,4.83%
6,38,Louis Armstrong New Orleans International Airport,MSY,New Orleans,New Orleans,LA,6537092,6309212,5931899,4017147,2632606,6717105,6565482,6005527,5569705,5329696,3.61%
7,39,Luis Muñoz Marín International Airport,SJU,San Juan,San Juan,PR,6490669,5985001,5039771,4738725,2362851,4590117,4033412,4163587,4343354,4218785,8.45%
8,40,Kansas City International Airport,MCI,Kansas City,Kansas City,MO,5915078,5654068,4796476,3795290,2167616,5759419,5935131,5744918,5391557,5135127,4.62%
9,41,Norman Y. Mineta San José International Airport,SJC,San Jose,San Francisco Bay Area,CA,5822019,5958855,5590137,3619690,2283186,7828885,7140616,6225148,5321603,4885690,-2.3%
10,42,San Antonio International Airport,SAT,San Antonio,San Antonio,TX,5466684,5336684,4751610,3677643,1919958,5022980,4844427,4521611,4179994,4091389,2.44%
11,43,Southwest Florida International Airport,RSW,Fort Myers,Southwest Florida,FL,5425293,4963269,5132694,5080805,2947139,5144467,4719568,4461304,4350650,4231134,9.31%
12,44,John Wayne Airport,SNA,Santa Ana,Greater Los Angeles,CA,5370273,5706332,5536313,3807205,1824836,5153276,5317149,5195047,5217242,4945175,-5.89%
13,45,Oakland San Francisco Bay Airport,OAK,Oakland,San Francisco Bay Area,CA,5292736,5520812,5506232,4011953,2271294,6560230,6798321,6530308,5934639,5506672,-4.13%
14,46,Indianapolis International Airport,IND,Indianapolis,Indianapolis,IN,5181947,4788376,4209416,3487100,1989126,4709183,4695040,4376432,4216766,3889567,8.22%
15,47,Cleveland Hopkins International Airport,CLE,Cleveland,Cleveland,OH,4950345,4803822,4237795,3552402,1990156,4894541,4836580,4562740,4205739,4083476,3.05%
16,48,Pittsburgh International Airport,PIT,Pittsburgh,Pittsburgh,PA,4862376,4493052,3918968,3069259,1742406,4715947,4670033,4327431,3986114,3890677,8.22%
17,49,Cincinnati Northern Kentucky International Air...,CVG,Cincinnati,Cincinnati,KY,4500414,4287722,3702997,3050597,1729395,4413457,4269258,3926158,3269979,3036697,4.96%
18,50,John Glenn Columbus International Airport,CMH,Columbus,Columbus,OH,4387395,4095189,3618555,2825259,1577596,4172067,4054572,3765007,3567864,3312496,7.14%
19,51,Palm Beach International Airport,PBI,West Palm Beach,Miami Metro,FL,4127211,3815977,3257730,2567897,1518732,3460429,3263042,3166532,3100624,3113485,8.16%
20,52,Jacksonville International Airport,JAX,Jacksonville,Jacksonville,FL,3749791,3619739,3177393,2425685,1367501,3479923,3118540,2759067,2799587,2716465,3.59%
21,53,Ontario International Airport,ONT,Ontario,Greater Los Angeles,CA,3494554,3181161,2840758,2201528,1237946,2723002,2499171,2247645,2127387,2089801,9.85%
22,54,Kahului Airport,OGG,Kahului,Maui,HI,3415615,3745866,4125311,2933315,1135141,3791807,3572133,3442189,3352813,3220753,-8.82%
23,55,Hollywood Burbank Airport,BUR,Burbank,Greater Los Angeles,CA,3383237,3132029,3054729,1942417,1056838,2988720,2680240,2402106,2077892,1973897,8.02%
24,56,Bradley International Airport,BDL,Hartford,Hartford,CT,3285194,3122212,2844713,2273259,1150033,3323614,3330734,3214976,2982194,2926047,5.22%
25,57,Charleston International Airport,CHS,Charleston,Charleston,SC,3115194,3032768,2608497,2015277,944660,2375868,2192893,1945699,1811695,1669988,2.72%
26,58,Milwaukee Mitchell International Airport,MKE,Milwaukee,Milwaukee,WI,3104054,2959840,2671281,2231010,1263385,3374073,3548817,3452544,3383271,3229876,4.87%
27,59,Ted Stevens Anchorage International Airport,ANC,Anchorage,Anchorage,AK,2767856,2681818,2604308,2184959,1157301,2713843,2642901,2556188,2563524,2525876,3.21%
28,60,Albuquerque International Sunport,ABQ,Albuquerque,Albuquerque,NM,2690218,2605163,2317836,1688646,868922,2641450,2647269,2412328,2341719,2323883,3.26%
29,61,Eppley Airfield,OMA,Omaha,Omaha,NE,2583212,2464418,2204395,1829912,1036245,2455274,2457087,2303223,2127387,2046155,4.82%
30,62,Buffalo Niagara International Airport,BUF,Buffalo,Buffalo–Niagara Falls,NY,2499295,2291995,2007508,1427891,703401,2459199,2523158,2348512,2313724,2331636,9.04%
31,63,Boise Airport,BOI,Boise,Boise,ID,2475370,2369164,2230467,1809000,991241,2057750,1943181,1777642,1633507,1487777,4.48%

#### Table2 - City column has the City & State together. 

##### Data Cleaning: Separating City and State Information

##### Problem
Table2's `City` column contains both city and state information combined together (e.g., "New York, NY").

##### Solution
To preserve the original data while preparing for separation, we rename the column and ensure it's in the correct format:

1. **Rename the column** from `City` to `City_Original` to preserve the original combined data
2. **Validate data type** to ensure `City_Original` is a Series (not a DataFrame)
3. **Preview the data** to verify the transformation

##### Next Steps
After this transformation, you can split `City_Original` into separate `City` and `State` columns using string manipulation methods.

In [173]:
# Rename the 'City' column to 'City_Original' to preserve the original city data
df_table2.rename(columns={'City': 'City_Original'}, inplace=True)

# Ensure 'City_Original' is a Series and not a DataFrame
if isinstance(df_table2['City_Original'], pd.DataFrame):
    # If it's a DataFrame, take the first column and replace the original column
    df_table2['City_Original'] = df_table2['City_Original'].iloc[:, 0]

# Display the first 5 values in the 'City_Original' column of df_table2
df_table2['City_Original'].head()

0                   Queens, New York
1            Los Angeles, California
2                     Miami, Florida
3    South San Francisco, California
4                 Newark, New Jersey
Name: City_Original, dtype: object

#### City and State Column Separation

This code processes the `City_Original` column in `df_table2`, which contains combined city and state information, and separates them into distinct columns.

**Steps:**

1. **Split the combined column**: The `City_Original` column is split at the first comma into city and state components
2. **Clean the data**: Both city and state values are stripped of extra whitespace and converted to title case
3. **Insert new columns**: `City` and `State` columns are added immediately after `City_Original`
4. **Standardize territories**: Special handling for Guam and Puerto Rico to ensure consistent naming
5. **Convert state names to codes**: Full state names are mapped to their 2-letter abbreviations using a comprehensive state mapping dictionary

**Result**: The dataframe now contains separate, standardized `City` and `State` columns with proper formatting and state abbreviations.

In [175]:
# Convert 'City_Original' column to string and split at the first comma into two new columns
split_cols = df_table2['City_Original'].astype(str).str.split(',', n=1, expand=True)

# Ensure the resulting DataFrame has exactly two columns labeled 0 and 1
split_cols = split_cols.reindex(columns=[0, 1])

# Display the first few rows to check the result
# split_cols.head()

# Clean the 'city' column - Convert to string, remove extra spaces, and capitalize each word
city_clean = split_cols[0].astype(str).str.strip().str.title()

# Clean the 'state' column - Convert to string, remove extra spaces, and capitalize each word
state_clean = split_cols[1].astype(str).str.strip().str.title()

# Find the column index of 'City_Original' in the dataframe
col_index = df_table2.columns.get_loc('City_Original')

# Insert a new column 'City' right after 'City_Original' with the cleaned city values
df_table2.insert(col_index + 1, 'City', city_clean)

# Insert a new column 'State' after the new 'City' column with the cleaned state values
df_table2.insert(col_index + 2, 'State', state_clean)

# Standardize 'State' values for Guam - If the 'State' column has any variations of 'Guam', set it explicitly to 'Guam'
df_table2.loc[df_table2['State'] == 'Guam', 'State'] = 'Guam'

# Standardize 'State' values for Puerto Rico - If the 'State' column has any variations of 'Puerto Rico', set it explicitly to 'Puerto Rico'
df_table2.loc[df_table2['State'] == 'Puerto Rico', 'State'] = 'Puerto Rico'

# Create a mapping dictionary for U.S. state names to their 2-letter codes
state_map = {
    'Alabama': 'AL', 'Alaska': 'AK', 'Arizona': 'AZ', 'Arkansas': 'AR',
    'California': 'CA', 'Colorado': 'CO', 'Connecticut': 'CT', 'Delaware': 'DE',
    'Florida': 'FL', 'Georgia': 'GA', 'Hawaii': 'HI', 'Idaho': 'ID',
    'Illinois': 'IL', 'Indiana': 'IN', 'Iowa': 'IA', 'Kansas': 'KS',
    'Kentucky': 'KY', 'Louisiana': 'LA', 'Maine': 'ME', 'Maryland': 'MD',
    'Massachusetts': 'MA', 'Michigan': 'MI', 'Minnesota': 'MN', 'Mississippi': 'MS',
    'Missouri': 'MO', 'Montana': 'MT', 'Nebraska': 'NE', 'Nevada': 'NV',
    'New Hampshire': 'NH', 'New Jersey': 'NJ', 'New Mexico': 'NM', 'New York': 'NY',
    'North Carolina': 'NC', 'North Dakota': 'ND', 'Ohio': 'OH', 'Oklahoma': 'OK',
    'Oregon': 'OR', 'Pennsylvania': 'PA', 'Rhode Island': 'RI',
    'South Carolina': 'SC', 'South Dakota': 'SD', 'Tennessee': 'TN',
    'Texas': 'TX', 'Utah': 'UT', 'Vermont': 'VT', 'Virginia': 'VA',
    'Washington': 'WA', 'West Virginia': 'WV', 'Wisconsin': 'WI', 'Wyoming': 'WY'
}

# Convert full state names in the 'State' column to 2-letter codes
# If a state name is not in the mapping, keep it as is
df_table2['State'] = df_table2['State'].map(state_map).fillna(df_table2['State'])

#### Data Preview: City Column Parsing

The `City` column in Table2 originally contains both city and state information combined. We've separated these into distinct columns for easier analysis.

Below, we preview the original combined column alongside the newly created `City` and `State` columns to verify the data parsing:

In [178]:
# Preview selected columns in the dataframe
df_table2[['City_Original', 'City', 'State']].head()

                     City_Original                 City State
0                 Queens, New York               Queens    NY
1          Los Angeles, California          Los Angeles    CA
2                   Miami, Florida                Miami    FL
3  South San Francisco, California  South San Francisco    CA
4               Newark, New Jersey               Newark    NJ

#### Busiest International Airports in the USA - Table2

This section displays the contents of the `df_table2` dataframe, which contains data about the busiest international airports in the United States.

The `display()` function renders the dataframe in an interactive, formatted table view that shows:
- Column headers
- Row data
- Proper alignment and styling

This is particularly useful in Jupyter notebooks, as it provides a more visually appealing output than the standard `print()` function.

In [179]:
# Display the contents of the dataframe 'df_table2' in a readable format
display(df_table2)

,Rank,Airport,City_Original,City,State,IATA_Code,Passengers_2024,Passengers_2023,Passengers_2022,Passengers_2021,Passengers_2020,Passengers_2019,Pct_Change_24_23
0,1,John F. Kennedy International Airport,"Queens, New York",Queens,NY,JFK,34765387,32481057,25178878,12466165,8219317,33432159,7.03%
1,2,Los Angeles International Airport,"Los Angeles, California",Los Angeles,CA,LAX,23438418,21503227,15940358,7862532,6246602,25210140,9.0%
2,3,Miami International Airport,"Miami, Florida",Miami,FL,MIA,23202731,21382328,18985551,11592445,6565834,20735658,8.51%
3,4,San Francisco International Airport,"South San Francisco, California",South San Francisco,CA,SFO,15083931,13224356,9298781,3139041,3210024,14357960,14.06%
4,5,Newark Liberty International Airport,"Newark, New Jersey",Newark,NJ,EWR,14690370,14080779,11344732,6250880,3688541,14087622,4.33%
5,6,O'Hare International Airport,"Chicago, Illinois",Chicago,IL,ORD,13865434,13152578,10746991,5148494,3481860,13412885,5.42%
6,7,Hartsfield Jackson Atlanta International Airport,"College Park, Georgia",College Park,GA,ATL,13813088,12088444,9543318,5474264,3347184,12268779,14.27%
7,8,Dallas Fort Worth International Airport,"Grapevine, Texas",Grapevine,TX,DFW,11841330,10691190,8992922,5852397,3268822,9103438,10.76%
8,9,George Bush Intercontinental Airport,"Houston, Texas",Houston,TX,IAH,11675134,11279214,9124043,6458473,3491935,10764589,3.51%
9,10,Washington Dulles International Airport,"Dulles, Virginia",Dulles,VA,IAD,10060851,8963807,6690447,3230027,1917510,7990292,12.24%
10,11,General Edward Lawrence Logan International Ai...,"Boston, Massachusetts",Boston,MA,BOS,8491518,7651625,5459853,2046561,1574712,7534504,10.98%
11,12,Orlando International Airport,"Orlando, Florida",Orlando,FL,MCO,7610776,6696949,5214203,1837706,1525177,6957048,13.65%
12,13,Fort Lauderdale Hollywood International Airport,"Fort Lauderdale, Florida",Fort Lauderdale,FL,FLL,6897993,7430312,6125500,4016553,2839383,8524251,-7.16%
13,14,Seattle Tacoma International Airport,"Seatac, Washington",Seatac,WA,SEA,6056779,5517422,4004180,1393603,1273179,5392147,9.78%
14,15,Charlotte Douglas International Airport,"Charlotte, North Carolina",Charlotte,NC,CLT,4623143,4140531,3183695,1989704,1069001,3405907,11.66%
15,16,Denver International Airport,"Denver, Colorado",Denver,CO,DEN,4444671,3823871,3222132,1856124,934563,3037012,16.23%
16,17,Philadelphia International Airport,"Philadelphia, Pennsylvania",Philadelphia,PA,PHL,3704176,3518548,2613240,988733,682030,3847253,5.28%
17,18,Harry Reid International Airport,"Paradise, Nevada",Paradise,NV,LAS,3592102,3133224,2439479,738257,711614,3462627,14.65%
18,19,Daniel K. Inouye International Airport,"Honolulu, Hawaii",Honolulu,HI,HNL,3533266,3134548,1565985,167502,1052697,5207875,12.72%
19,20,Detroit Metropolitan Wayne County Airport,"Romulus, Michigan",Romulus,MI,DTW,3353501,2835905,2092098,966375,873744,3717775,18.25%
20,21,Minneapolis Saint Paul International Airport,"Saint Paul, Minnesota",Saint Paul,MN,MSP,3320850,2817694,1942385,673759,835721,3144386,17.86%
21,22,Phoenix Sky Harbor International Airport,"Phoenix, Arizona",Phoenix,AZ,PHX,2821736,2481029,1957189,1223856,750138,1958468,13.73%
22,23,Laguardia Airport,"Queens, New York",Queens,NY,LGA,1686395,1793314,1334733,309217,393011,2206518,-5.96%
23,24,Luis Muñoz Marín International Airport,"San Juan, Puerto Rico",San Juan,Puerto Rico,SJU,1458172,1158996,802613,468287,253114,866088,25.81%
24,25,Tampa International Airport,"Tampa, Florida",Tampa,FL,TPA,1384192,1178288,780245,167847,258738,1039740,17.47%
25,26,Antonio B. Won Pat International Airport,"Tamuning, Guam",Tamuning,Guam,GUM,1342793,1192615,557359,98630,431890,2327930,12.59%
26,27,Salt Lake City International Airport,"Salt Lake City, Utah",Salt Lake City,UT,SLC,1311617,1250372,846680,578710,302640,1034704,4.9%
27,28,Baltimore Washington International Airport,"Linthicum Heights, Maryland",Linthicum Heights,MD,BWI,1156882,1201948,1006908,651636,341035,1104208,-3.75%
28,29,Austin Bergstrom International Airport,"Austin, Texas",Austin,TX,AUS,1064668,987214,818072,230835,81433,512989,7.85%
29,30,San Diego International Airport,"San Diego, California",San Diego,CA,SAN,995537,904162,538005,200233,247218,1044516,10.11%

### Ethical Implications of Data Wrangling

**Data Transformations and Sources:** This project involved several key transformations on data scraped from Wikipedia's "List of the Busiest Airports in the United States" page, including renaming columns, splitting location data into city and state fields, converting passenger counts to numeric values, handling missing values, and calculating year-over-year percentage changes. The data was sourced from Wikipedia, which aggregates information from credible sources like FAA statistics and airport authorities. Data was acquired ethically using standard web scraping practices with appropriate headers, accessing publicly available information without violating Wikipedia's terms of service.

**Assumptions and Legal Considerations:** Several assumptions were made during data cleaning: missing values were converted to NaN, the Wikipedia data accurately reflected official statistics, city/state parsing logic was correct, and percentage calculations were meaningful despite COVID-19 data collection anomalies. While there are no legal restrictions on using publicly available Wikipedia data for academic analysis, ethical practices require proper attribution and transparent documentation of all transformations.

**Risks and Mitigation:** The primary risks include potential misrepresentation of airport rankings if source data contained errors, amplification of Wikipedia's crowd-sourced data quality issues, and misleading calculated metrics without proper context. To mitigate these concerns, all transformations are fully documented and reproducible in the notebook, the Wikipedia source is clearly cited, assumptions are explicitly stated, and the analysis acknowledges limitations of using secondary-source data that may not represent official FAA statistics directly.